# Configuration Jekyll
title: Votre Site
description: Description de votre site
baseurl: "" # le sous-chemin de votre site, ex: /blog
url: "https://votre-nom-utilisateur.github.io" # l'URL de base de votre site

# Build settings
markdown: kramdown
highlighter: rouge

# Inclure tous les dossiers et fichiers statiques
include:
  - font
  - img
  - txt
  - "*.html"

# Exclure les fichiers de développement
exclude:
  - .github
  - README.md
  - Gemfile
  - Gemfile.lock

# Collections ou autres paramètres si nécessaire
plugins:
  - jekyll-feed
  - jekyll-sitemap
